name: Newman Tests

on: [push, pull_request]

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Install Node.js
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      # Install Newman and reporter
      - name: Install Newman and Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # Create directory for results
      - name: Create Results Directory
        run: mkdir -p testResults

      # Run Postman collection
      - name: Run API Tests
        run: |
          newman run "Restful Booker BVT.postman_collection.json" \
            -e "Production.postman_environment.json" \
            -r htmlextra \
            --reporter-htmlextra-export testResults/htmlreport.html

      # Upload results as artifact
      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: RunReports
          path: testResults
